### ISSUE TITLE
HTTP Range support would be nice

### ISSUE THREAD

**Issue by divinity76** [songlipeng2003/php-x-sendfile#6]
ref https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

**Comment by songlipeng2003** [comment]
This is good idea, thanks. I will evaluate how to do.

**Comment by divinity76** [comment]
you can use code from https://codereview.stackexchange.com/questions/280259/php-readfile-with-304-not-modified-and-http-206-partial-content-support-httpr 
if you want ^^ (might be a bit premature right now because it's still in code review)

**Comment by divinity76** [comment]
possible implementation in #8
